### PR TITLE
Validate user input on location steps as YAML

### PR DESCRIPTION
**Pull request by alexweininger**
This prevents the workflow from containing values like `""app""` which are YAML syntax errors.

This is related to #411, but I don't consider it a fix. A real fix is coming soon...

### CODE REVIEW

**Comment by nturinski** [comment]
What do you think if we just validate the yaml settings upfront in the prompt step rather than fixing it retroactively?

**Comment by alexweininger** [comment]
> What do you think if we just validate the yaml settings upfront in the prompt step rather than fixing it retroactively?

I like that approach much better. I was also looking for a package that could just validate a YAML string value since that would be the most robust option.

Would we just say any value with double quotes is invalid? Should we allow them to escape the quotes?

**Comment by nturinski** [comment]
Actually, we already have this package installed: https://www.npmjs.com/package/yaml

It has a `stringify` method which we could use to convert the input as well.

**Comment by alexweininger** [comment]
Sweet, using the YAML package I'm validating the input as YAML and it works really well.

image

**Review by nturinski — APPROVED** [review]

**Pull request merged**
